sudo: required
dist: trusty
language: csharp
mono:
  - latest
solution: taglib-sharp.sln

install:
  - sudo apt-get update -qq > /dev/null
  - nuget restore taglib-sharp.sln

script:
  - ./autogen.sh
  - xbuild taglib-sharp.sln
  - mono packages/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe --labels=All tests/tests.dll
